_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 16
                - 22
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
env_name:
    value: L63-ENKF
policy_type:
    value: PPO-shared
total_timesteps:
    value: 10000000
